name: Nightly-Nightly-Check

on:
  schedule:
    # nightly tests
    - cron: "0 0 * * *"
  # Be able to run manually
  workflow_dispatch:

jobs:
  test:
    if: (github.event_name == 'schedule'  && matrix.cfg.nightly) || github.event_name != 'schedule' 
    name: Test on ${{ matrix.cfg.os }}, Python ${{ matrix.cfg.python-version }}, OpenMM ${{ matrix.cfg.openmm }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-latest, python-version: 3.7, openmm: latest }
          - { os: ubuntu-latest, python-version: 3.8, openmm: latest }
          - { os: ubuntu-latest, python-version: 3.7, openmm: nightly }
          - { os: ubuntu-latest, python-version: 3.8, openmm: nightly }
          - { os: ubuntu-latest, python-version: 3.7, openmm: conda-forge }
          - { os: ubuntu-latest, python-version: 3.8, openmm: conda-forge }

    env:
      OPENMM: ${{ matrix.cfg.openmm }}
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt

    steps:
      - uses: actions/checkout@v2

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      # More info on options: https://github.com/conda-incubator/setup-miniconda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: devtools/conda-envs/test_env.yaml
          channels: conda-forge,defaults,omnia-dev,openeye
          activate-environment: test
          auto-update-conda: true
          auto-activate-base: false
          show-channel-urls: true

      - name: Refine test environment
        shell: bash -l {0}
        run: |
          case ${{ matrix.cfg.openmm }} in
            latest)
              echo "Using latest release OpenMM."
              conda install --quiet -c conda-forge openmm;;
           #rc) # We can uncomment this case when we have this label on conda-forge
             #echo "Using OpenMM rc" 
             #conda install --quiet -c conda-forge/label/openmm_rc openmm;;
            nightly)
              echo "Using OpenMM nightly dev build."
              conda install --quiet -c omnia-dev openmm;;
          esac

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -v .

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Decrypt OpenEye license
        shell: bash -l {0}
        env:
          OE_LICENSE_TEXT: ${{ secrets.OE_LICENSE }}
        run: |
          echo "${OE_LICENSE_TEXT}" > ${OE_LICENSE}
          python -c "import openeye; assert openeye.oechem.OEChemIsLicensed(), 'OpenEye license checks failed!'"

      - name: Test the package
        shell: bash -l {0}
        run: |
          export OE_LICENSE="$HOME/oe_license.txt"
          export TRAVIS=true
          pushd .
          nosetests perses --with-coverage --cover-package=perses --verbosity=3 --with-timer -a '!advanced' --cover-xml --cover-xml-file=./coverage.xml
          popd

      - name: Make an issue
      - uses: JasonEtco/create-an-issue@v2
        if: ${{ failure() }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
             assignees: mikemhenry
             filename: .github/nightly-fail.md
